### ISSUE TITLE
supermassive v3 Roadmap

### ISSUE THREAD

**Issue by freiksenet** [microsoft/graphitation#315]
- [x] @defer / @stream
  - [x] @defer and @stream support
  - [x] unify subscription into execution
- [x] move implicit resolvers into document
- [x] change document format to use SDL in directive instead of inline nodes

**Comment by vladar** [comment]
Done via https://github.com/microsoft/graphitation/pull/356
